<a href="https://colab.research.google.com/github/JamesKevinStar/ImplementacionesRedesNeuronales/blob/main/Perceptr%C3%B3n%20Multi%20Capa/Tarea_N%C2%B05_Implementaci%C3%B3n_Perceptr%C3%B3n_MultiCapa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Implementación del Perceptrón Multicapa
```
Docente     : Luis Beltran Palma Ttito
Alumnos     : James Kevin Estrella Vilca (182909) - Raísa Melina Peña Luque (182927)
Lugar       : Cusco, Perú, 2022
Universidad : Universidad Nacional de San Antonio Abad del Cusco
```

# 1. Importar Librerías

In [ ]:
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
import pandas as pd
import numpy as np
import statistics
import random
import pylab

from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
from sklearn.metrics import confusion_matrix
from matplotlib import pylab

%matplotlib inline

# 2. Leer Datos

In [ ]:
data = pd.read_csv("iris.csv")
data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# 3. Preparación de Datos

## A. Convertir Categórico a Numérico

In [ ]:
def Categórico_Numérico(datos):
    datos = datos.astype("category")
    return datos.astype("category").cat.codes

In [ ]:
data.astype("category")
data['Species'] = Categórico_Numérico(data['Species'])
data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

## B. Normalización

In [ ]:
def Normalización(datos):
    return (datos - datos.min())/(datos.max() - datos.min())

In [ ]:
data.loc[:,["Sepal.Length","Sepal.Width","Petal.Length","Petal.Width"]] = Normalización(data.loc[:,["Sepal.Length","Sepal.Width","Petal.Length","Petal.Width"]])
data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0      0.222222     0.625000      0.067797     0.041667        0
1      0.166667     0.416667      0.067797     0.041667        0
2      0.111111     0.500000      0.050847     0.041667        0
3      0.083333     0.458333      0.084746     0.041667        0
4      0.194444     0.666667      0.067797     0.041667        0

# 4. Separación de Datos de Test - Train

In [ ]:
def Separar_Datos(Data, Categoría, Proporción, Semilla):
    X = Data.drop([Categoría],axis=1).values
    Y = Data[Categoría].values
    Dif = len(set(Y))
    Clases = to_categorical(Y.tolist(), Dif)
    Clases_Dif = []
    for i in range(len(Clases)):
        if len(Clases_Dif) == 0:
            Clases_Dif.append(Clases[i].tolist())
        else:
            if Clases[i].tolist() not in Clases_Dif:
                Clases_Dif.append(Clases[i].tolist())
    Train_Data_X, Test_Data_X, Train_Data_Y, Test_Data_Y = train_test_split(X, Y, test_size=Proporción, random_state=Semilla)
    return Train_Data_X, Train_Data_Y, Test_Data_X, Test_Data_Y, Dif, Clases_Dif

In [ ]:
Train_Data_X, Train_Data_Y, Test_Data_X, Test_Data_Y, Valores_Diferentes, Clases = Separar_Datos(data, "Species", 0.1, 20000901)

In [ ]:
print(Clases)

[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]


In [ ]:
def Ordenar_Clases(Clases):
    Clases = sorted(Clases, key=lambda x: x.index(1.0))
    return Clases

In [ ]:
Clases = Ordenar_Clases(Clases)
print(Clases)

[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]


In [ ]:
Train_Data_X

array([[0.47222222, 0.41666667, 0.6440678 , 0.70833333],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.22222222, 0.70833333, 0.08474576, 0.125     ],
       [0.44444444, 0.41666667, 0.54237288, 0.58333333],
       [0.05555556, 0.125     , 0.05084746, 0.08333333],
       [0.55555556, 0.33333333, 0.69491525, 0.58333333],
       [0.16666667, 0.45833333, 0.08474576, 0.04166667],
       [0.72222222, 0.45833333, 0.66101695, 0.58333333],
       [0.69444444, 0.41666667, 0.76271186, 0.83333333],
       [0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.47222222, 0.08333333, 0.6779661 , 0.58333333],
       [0.41666667, 0.33333333, 0.69491525, 0.95833333],
       [0.80555556, 0.41666667, 0.81355932, 0.625     ],
       [0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.52777778, 0.375     , 0.55932203, 0.5       ],
       [0.13888889, 0.58333333, 0.15254237, 0.04166667],
       [0.58333333, 0.29166667,

In [ ]:
Train_Data_Y

array([2, 0, 2, 0, 1, 0, 2, 0, 1, 2, 0, 2, 2, 2, 1, 1, 0, 2, 1, 2, 1, 0,
       0, 1, 0, 1, 1, 2, 0, 2, 1, 0, 2, 0, 0, 0, 2, 0, 1, 1, 0, 1, 2, 0,
       0, 1, 0, 1, 1, 1, 1, 2, 2, 2, 1, 2, 0, 2, 1, 1, 1, 0, 0, 0, 2, 1,
       0, 1, 0, 2, 0, 1, 2, 0, 2, 0, 1, 2, 1, 0, 2, 2, 0, 2, 0, 1, 0, 2,
       1, 1, 1, 2, 2, 2, 0, 1, 2, 2, 2, 2, 1, 2, 0, 0, 0, 2, 2, 0, 1, 0,
       1, 1, 2, 0, 2, 2, 2, 1, 2, 1, 2, 0, 2, 0, 2, 0, 1, 0, 1, 2, 1, 1,
       1, 0, 1], dtype=int8)

# 5. Conversión del Atributo de Salida en Binario

In [ ]:
Train_Data_Y = to_categorical(Train_Data_Y, Valores_Diferentes)
print(Train_Data_Y)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0.

In [ ]:
Test_Data_Y

array([0, 1, 0, 2, 0, 1, 0, 1, 0, 2, 1, 1, 2, 1, 0], dtype=int8)

In [ ]:
Test_Data_Y = to_categorical(Test_Data_Y, Valores_Diferentes)
print(Test_Data_Y)

[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


# 6. Implementación del Perceptrón Multicapa

## A. Función de Activación

In [ ]:
def Función_Activación_Sigmoide(X):
    return 1/(1+np.exp(X*-1))

## B. Función para Generar Pesos y Sesgo

In [ ]:
def Generar_Pesos_Sesgo(Capas):
    W = []
    for k in range(len(Capas)-1):
        SW = [[random.uniform(-1,1) for i in range(Capas[k+1])] for j in range(Capas[k]+1)]
        W.append(SW)
    return W

## C. Escoger par Aleatorio

In [ ]:
def Seleccionar_Par_Aleatorio(X, Y):
    value = random.randint(0,len(X)-1)
    X_Prueba = X[value]
    Y_Prueba = Y[value]
    return X_Prueba, Y_Prueba

## D. Calcular Producto Punto

In [ ]:
def Calcular_Producto_Punto(X,W):
    Value = 0
    for i in range(len(W)-1):
        Value = X[i]*W[i] + Value
    return Value + W[len(W)-1]

## E. Propagación hacia Adelante

In [ ]:
def Foward_Propagation(X,W,Capas):
    Entradas_Originales = X
    Salidas_Generales = []
    for i in range(len(Capas)-1):
        Salidas_Generales.append(Entradas_Originales)
        Entradas_Nuevas = []
        for j in range(Capas[i+1]):
            P1 = [k for k in W[i]]
            P2 = [k[j] for k in P1]
            PP = Calcular_Producto_Punto(Entradas_Originales,P2)
            Salida = Función_Activación_Sigmoide(PP)
            Entradas_Nuevas.append(Salida)
        Entradas_Originales = Entradas_Nuevas  
    return Salidas_Generales, Entradas_Originales

## F. Calcular Error Cuadrático Medio

In [ ]:
def Error_Cuadrático(Valor_Obtenido, Valor_Deseado):
    EC = 0
    for i in range(len(Valor_Obtenido)):
        EC = EC + (Valor_Deseado[i] - Valor_Obtenido[i])**2
    return EC/(len(Valor_Obtenido)*2)

## G. Calcular Gradiente

In [ ]:
def Derivada_Sigmoide(Y):
    return Y*(1-Y)

In [ ]:
def Gradiente_Salida(D, Y):
    return (D-Y)*Derivada_Sigmoide(Y)

In [ ]:
def Gradiente_Proceso(Y, W, Sigmas_Anterior):
    Sigmas = []
    for i in range(len(W)-1):
        Suma = 0
        for j in range(len(Sigmas_Anterior)):
            Suma = Suma + Sigmas_Anterior[j]*W[i][j]
        Sigmas.append(Suma*Derivada_Sigmoide(Y[i]))
    return Sigmas

## H. Actualizar Pesos y Biases

In [ ]:
def Actualizar_Pesos_y_Bías(W, Coef, Salidas, Gradientes):
    for i in range(len(W[0])):
        for j in range(len(W)):
            if j != len(W)-1:
                W[j][i] = W[j][i] + Coef*Gradientes[i]*Salidas[j]
            else:
                W[j][i] = W[j][i] + Coef*Gradientes[i]
    return W

## I. Propagación hacia Atrás

In [ ]:
def Backward_Propagation(Capas, Salidas_G, Salidas_F, W, Coef_Apren, D):
    Sigmas_Salidas = []
    for i in range(len(D)):
        Gradiente = Gradiente_Salida(D[i],Salidas_F[i])
        Sigmas_Salidas.append(Gradiente) 
    for i in range(len(Capas)-1):
        if i == 0:
            W[len(Capas)-2-i] = Actualizar_Pesos_y_Bías(W[len(Capas)-2-i], Coef_Apren, Salidas_G[len(Capas)-2-i], Sigmas_Salidas)
        else:
            Sigmas_Salidas = Gradiente_Proceso(Salidas_G[len(Capas)-1-i],W[len(Capas)-1-i],Sigmas_Salidas)
            W[len(Capas)-2-i] = Actualizar_Pesos_y_Bías(W[len(Capas)-2-i], Coef_Apren, Salidas_G[len(Capas)-2-i], Sigmas_Salidas)
    return W

# 7. Diseño de la Arquitectura

In [ ]:
Capas = [4,6,5,3]

# 8. Entrenar Perceptrón Multicapa

In [ ]:
def Entrenar_Perceptrón_Multicapa(Épocas, Coef_Aprendizaje, X, Y, Capas):
    W = Generar_Pesos_Sesgo(Capas)
    AX, AY = Seleccionar_Par_Aleatorio(X, Y)
    SG, SF = Foward_Propagation(AX,W,Capas)
    Error = Error_Cuadrático(SF,AY)
    for i in range(Épocas):
        for j in range(len(X)):
            W = Backward_Propagation(Capas, SG, SF, W, Coef_Aprendizaje, AY)
            AX = X[j]
            AY = Y[j]
            SG, SF = Foward_Propagation(AX,W,Capas)
            Error = Error_Cuadrático(SF,AY)
    print("El error final es {}".format(Error))
    return W

In [ ]:
W = Entrenar_Perceptrón_Multicapa(300, 0.1, Train_Data_X, Train_Data_Y, Capas)
print(W)

El error final es 0.0007883078447404893
[[[-0.38898798093112585, 1.4774873568101061, 0.30487710681588837, 1.4737162288236947, -0.2831749090383395, 0.4585813014620412], [-2.4276024511003627, 0.36248328961302706, -1.2870746980095287, 1.4828469779462221, 0.6953983204641683, -2.7788074461496666], [2.7224769178933883, -1.3753904135057569, 1.9381426795633763, -3.8118165914148454, -1.2226198144703075, 2.959896144194085], [3.0657700481587637, -3.130781397061327, 2.3834070163809575, -4.511598225869253, -3.0336854813728933, 2.0216496745622794], [-1.8520145108836275, 1.7070950544003942, -1.7427527443202007, 4.011504109559097, 2.138981322425809, -1.2536786785898102]], [[-3.642618257462711, -2.2638653130965896, -3.434686891234759, 1.9423819243503593, 0.8972595608816841], [0.881146043382575, 0.3368372012615803, 3.7770588195843695, -0.7628054337735332, -0.21145799766996634], [-2.588836500691699, -0.157243297902005, -3.0316209929154483, 0.24971056714188913, 1.1174704412769219], [2.0678474218036222, 0.

# 9. Probar Perceptrón Multicapa

In [ ]:
def Test_Perceptrón_Multicapa(W, X, Y, Capas, Clases):
    Etiquetas_Obtenidas = []
    Etiquetas_Reales = []
    Y = Y.tolist()
    for i in range(len(Y)):
        SG, SF = Foward_Propagation(X[i].tolist(),W,Capas)
        Max = max(SF)
        for k in range(len(SF)):
            if SF[k] == Max:
                Etiquetas_Obtenidas.append(k+1)
                        
        for j in range(len(Clases)):
            if Y[i] == Clases[j]:
                Etiquetas_Reales.append(j+1)
            
    return Etiquetas_Obtenidas, Etiquetas_Reales

In [ ]:
EO, ER = Test_Perceptrón_Multicapa(W, Test_Data_X, Test_Data_Y, Capas, Clases)

# 10. Matriz de Confusión

In [ ]:
def Matriz_Confusión(EO, ER):
    print(confusion_matrix(ER, EO))

In [ ]:
Matriz_Confusión(EO, ER)

[[6 0 0]
 [0 6 0]
 [0 0 3]]


# 11. Métrica

In [ ]:
def Accuracy(EO, ER):
    Cont = 0
    for i in range(len(EO)):
        if ER[i] == EO[i]:
            Cont += 1
    print("El Accuracy es {}".format(Cont/len(EO)))

In [ ]:
Accuracy(EO, ER)

El Accuracy es 1.0


# 12. Predicción

In [ ]:
def Predecir(X, W, Capas, Clases):
    SG, SF = Foward_Propagation(X,W,Capas)
    Max = max(SF)
    for k in range(len(SF)):
        if SF[k] == Max:
            SF[k] = 1
        else:
            SF[k] = 0
    for i in range(len(Clases)):
        if SF == Clases[i]:
            print("La predicción {} es de la clase {}".format(SF,i+1))

In [ ]:
Predecir([0.3,0.5,0.9,0.1],W,Capas,Clases)

La predicción [0, 1, 0] es de la clase 2


# 13. Experimentación

## A. DataSet Wine

In [ ]:
data = pd.read_csv("wine.csv")
data.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6        127           2.80   
1    13.20        1.78  2.14               11.2        100           2.65   
2    13.16        2.36  2.67               18.6        101           2.80   
3    14.37        1.95  2.50               16.8        113           3.85   
4    13.24        2.59  2.87               21.0        118           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280_OD315  Proline  class  
0         3.92     1065      1  
1         3.40     1050      1  
2         3.17     1185      1  
3         3.45     1480      1  
4         2.93      735      1

In [ ]:
data.loc[:,["Alcohol","Malic acid","Ash","Alcalinity of ash","Magnesium","Total phenols","Flavanoids","Nonflavanoid phenols","Proanthocyanins","Color intensity","Hue","OD280_OD315","Proline"]] = Normalización(data.loc[:,["Alcohol","Malic acid","Ash","Alcalinity of ash","Magnesium","Total phenols","Flavanoids","Nonflavanoid phenols","Proanthocyanins","Color intensity","Hue","OD280_OD315","Proline"]])
data.head()

Alcohol  Malic acid       Ash  Alcalinity of ash  Magnesium  \
0  0.842105    0.191700  0.572193           0.257732   0.619565   
1  0.571053    0.205534  0.417112           0.030928   0.326087   
2  0.560526    0.320158  0.700535           0.412371   0.336957   
3  0.878947    0.239130  0.609626           0.319588   0.467391   
4  0.581579    0.365613  0.807487           0.536082   0.521739   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0       0.627586    0.573840              0.283019         0.593060   
1       0.575862    0.510549              0.245283         0.274448   
2       0.627586    0.611814              0.320755         0.757098   
3       0.989655    0.664557              0.207547         0.558360   
4       0.627586    0.495781              0.490566         0.444795   

   Color intensity       Hue  OD280_OD315   Proline  class  
0         0.372014  0.455285     0.970696  0.561341      1  
1         0.264505  0.463415     0.780220  0.550642      1  
2         0.375427  0.447154     0.695971  0.646933      1  
3         0.556314  0.308943     0.798535  0.857347      1  
4         0.259386  0.455285     0.608059  0.325963      1

In [ ]:
data['class'] = data['class'].replace({1: 0, 2: 1, 3:2})
data.head()

Alcohol  Malic acid       Ash  Alcalinity of ash  Magnesium  \
0  0.842105    0.191700  0.572193           0.257732   0.619565   
1  0.571053    0.205534  0.417112           0.030928   0.326087   
2  0.560526    0.320158  0.700535           0.412371   0.336957   
3  0.878947    0.239130  0.609626           0.319588   0.467391   
4  0.581579    0.365613  0.807487           0.536082   0.521739   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0       0.627586    0.573840              0.283019         0.593060   
1       0.575862    0.510549              0.245283         0.274448   
2       0.627586    0.611814              0.320755         0.757098   
3       0.989655    0.664557              0.207547         0.558360   
4       0.627586    0.495781              0.490566         0.444795   

   Color intensity       Hue  OD280_OD315   Proline  class  
0         0.372014  0.455285     0.970696  0.561341      0  
1         0.264505  0.463415     0.780220  0.550642      0  
2         0.375427  0.447154     0.695971  0.646933      0  
3         0.556314  0.308943     0.798535  0.857347      0  
4         0.259386  0.455285     0.608059  0.325963      0

In [ ]:
Train_Data_X, Train_Data_Y, Test_Data_X, Test_Data_Y, Valores_Diferentes, Clases = Separar_Datos(data, "class", 0.2, 20000901)
print(Clases)

[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]


In [ ]:
Clases = Ordenar_Clases(Clases)
print(Clases)

[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]


In [ ]:
Train_Data_X

array([[0.73684211, 0.16403162, 0.67379679, ..., 0.52845528, 0.47619048,
        0.60770328],
       [0.70789474, 0.13636364, 0.60962567, ..., 0.33333333, 0.58608059,
        0.71825963],
       [0.67105263, 0.18181818, 0.53475936, ..., 0.49593496, 0.58974359,
        0.88231098],
       ...,
       [0.57894737, 0.50592885, 0.49197861, ..., 0.06504065, 0.08791209,
        0.2831669 ],
       [0.78684211, 0.18577075, 0.45454545, ..., 0.45528455, 0.84981685,
        0.53994294],
       [0.37894737, 0.1541502 , 0.44919786, ..., 0.55284553, 0.4981685 ,
        0.4700428 ]])

In [ ]:
Train_Data_Y

array([0, 0, 0, 1, 0, 1, 2, 1, 1, 0, 0, 2, 0, 2, 2, 2, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 1,
       0, 0, 1, 0, 2, 1, 2, 1, 2, 1, 0, 2, 1, 1, 2, 1, 2, 2, 2, 1, 0, 1,
       2, 2, 1, 1, 0, 0, 2, 1, 0, 0, 0, 1, 1, 2, 0, 1, 0, 0, 2, 1, 0, 2,
       1, 0, 0, 2, 0, 2, 1, 2, 1, 0, 0, 2, 0, 1, 1, 2, 2, 1, 2, 2, 2, 0,
       2, 0, 1, 2, 1, 1, 0, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 0, 1, 0, 2, 0,
       1, 0, 1, 2, 0, 1, 0, 2, 0, 1])

In [ ]:
Train_Data_Y = to_categorical(Train_Data_Y, Valores_Diferentes)
print(Train_Data_Y)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1.

In [ ]:
Test_Data_Y

array([1, 2, 1, 0, 2, 1, 1, 0, 0, 2, 1, 2, 2, 0, 0, 2, 1, 2, 2, 1, 0, 0,
       2, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0])

In [ ]:
Test_Data_Y = to_categorical(Test_Data_Y, Valores_Diferentes)
print(Test_Data_Y)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [ ]:
Capas = [11,12,3]

In [ ]:
W = Entrenar_Perceptrón_Multicapa(250, 0.1, Train_Data_X, Train_Data_Y, Capas)
print(W)

El error final es 0.0022711519367837395
[[[0.9721246055273913, -1.9215631080678783, -1.799144863855728, -2.524454415375891, -2.0970640726203804, -1.5732495393537715, 0.6713383558135281, 3.57820167719144, 1.6835109625967177, -0.6412217272755127, -0.525874472352652, 0.703468504372081], [0.1157946170336051, -0.027793763413539323, 0.2439052119630461, -0.5826589508322709, -0.7587364670239258, -0.3628788146503412, 0.10219474139789374, 0.14769927703342264, 0.5129961544968079, -0.72325049660098, 0.13295107983310955, 1.1691546307858498], [1.8648636679349917, -3.297746915144937, -2.878318531505997, -2.0311461802049595, -0.9522464991868919, 0.055933668759659695, -0.22605088061548176, 2.8652817068125422, 0.8190835828239328, -0.18336575137976188, 0.1397216851300711, 1.1041028225393612], [-0.19195661036413655, 1.4401658118881688, 1.4433576340223209, 1.4743491346644066, 0.533686850933967, 1.426627291234957, -0.671470129224972, -4.053187278671278, -0.8050751841584568, -1.3919827243154081, 0.3391901661

In [ ]:
EO, ER = Test_Perceptrón_Multicapa(W, Test_Data_X, Test_Data_Y, Capas, Clases)

In [ ]:
Matriz_Confusión(EO, ER)

[[15  0  0]
 [ 2 10  0]
 [ 0  0  9]]


In [ ]:
Accuracy(EO, ER)

El Accuracy es 0.9444444444444444


In [ ]:
Predecir([0.3,0.5,0.6,0.9,0.4,0.0,0.2,0.6,0.1,0.8,0.3],W,Capas,Clases)

La predicción [0, 0, 1] es de la clase 3


## B. DataSet Dígito

In [ ]:
data = pd.read_csv("digito8x8.csv")
data.head()

P1  P2  P3  P4  P5  P6  P7  P8  P9  P10  ...  P56  P57  P58  P59  P60  P61  \
0   0   1   6  15  12   1   0   0   0    7  ...    0    0    0    6   14    7   
1   0   0  10  16   6   0   0   0   0    7  ...    0    0    0   10   16   15   
2   0   0   8  15  16  13   0   0   0    1  ...    0    0    0    9   14    0   
3   0   0   0   3  11  16   0   0   0    0  ...    0    0    0    0    1   15   
4   0   0   5  14   4   0   0   0   0    0  ...    0    0    0    4   12   14   

   P62  P63  P64  digito  
0    1    0    0       0  
1    3    0    0       0  
2    0    0    0       7  
3    2    0    0       4  
4    7    0    0       6  

[5 rows x 65 columns]

In [ ]:
data.iloc[:,0:64] = Normalización(data.iloc[:,0:64])
data.head()

P1     P2      P3      P4      P5      P6   P7   P8   P9     P10  ...  P56  \
0 NaN  0.125  0.3750  0.9375  0.7500  0.0625  0.0  0.0  0.0  0.4375  ...  0.0   
1 NaN  0.000  0.6250  1.0000  0.3750  0.0000  0.0  0.0  0.0  0.4375  ...  0.0   
2 NaN  0.000  0.5000  0.9375  1.0000  0.8125  0.0  0.0  0.0  0.0625  ...  0.0   
3 NaN  0.000  0.0000  0.1875  0.6875  1.0000  0.0  0.0  0.0  0.0000  ...  0.0   
4 NaN  0.000  0.3125  0.8750  0.2500  0.0000  0.0  0.0  0.0  0.0000  ...  0.0   

   P57  P58     P59     P60     P61     P62  P63  P64  digito  
0  0.0  0.0  0.3750  0.8750  0.4375  0.0625  0.0  0.0       0  
1  0.0  0.0  0.6250  1.0000  0.9375  0.1875  0.0  0.0       0  
2  0.0  0.0  0.5625  0.8750  0.0000  0.0000  0.0  0.0       7  
3  0.0  0.0  0.0000  0.0625  0.9375  0.1250  0.0  0.0       4  
4  0.0  0.0  0.2500  0.7500  0.8750  0.4375  0.0  0.0       6  

[5 rows x 65 columns]

In [ ]:
data.fillna(0, inplace=True)
data.head()

P1     P2      P3      P4      P5      P6   P7   P8   P9     P10  ...  \
0  0.0  0.125  0.3750  0.9375  0.7500  0.0625  0.0  0.0  0.0  0.4375  ...   
1  0.0  0.000  0.6250  1.0000  0.3750  0.0000  0.0  0.0  0.0  0.4375  ...   
2  0.0  0.000  0.5000  0.9375  1.0000  0.8125  0.0  0.0  0.0  0.0625  ...   
3  0.0  0.000  0.0000  0.1875  0.6875  1.0000  0.0  0.0  0.0  0.0000  ...   
4  0.0  0.000  0.3125  0.8750  0.2500  0.0000  0.0  0.0  0.0  0.0000  ...   

   P56  P57  P58     P59     P60     P61     P62  P63  P64  digito  
0  0.0  0.0  0.0  0.3750  0.8750  0.4375  0.0625  0.0  0.0       0  
1  0.0  0.0  0.0  0.6250  1.0000  0.9375  0.1875  0.0  0.0       0  
2  0.0  0.0  0.0  0.5625  0.8750  0.0000  0.0000  0.0  0.0       7  
3  0.0  0.0  0.0  0.0000  0.0625  0.9375  0.1250  0.0  0.0       4  
4  0.0  0.0  0.0  0.2500  0.7500  0.8750  0.4375  0.0  0.0       6  

[5 rows x 65 columns]

In [ ]:
Train_Data_X, Train_Data_Y, Test_Data_X, Test_Data_Y, Valores_Diferentes, Clases = Separar_Datos(data, "digito", 0.2, 20000901)
print(Clases)

[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0], [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]


In [ ]:
Clases = sorted(Clases, key=lambda x: x.index(1.0))
print(Clases)

[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]]


In [ ]:
Train_Data_X

array([[0.    , 0.    , 0.    , ..., 0.9375, 0.625 , 0.    ],
       [0.    , 0.    , 0.375 , ..., 0.3125, 0.    , 0.    ],
       [0.    , 0.    , 0.25  , ..., 0.8125, 0.0625, 0.    ],
       ...,
       [0.    , 0.    , 0.    , ..., 0.9375, 0.3125, 0.    ],
       [0.    , 0.    , 0.    , ..., 0.875 , 0.0625, 0.    ],
       [0.    , 0.    , 0.    , ..., 1.    , 0.75  , 0.    ]])

In [ ]:
Train_Data_Y

array([6, 3, 3, ..., 6, 6, 6])

In [ ]:
Train_Data_Y = to_categorical(Train_Data_Y, Valores_Diferentes)
print(Train_Data_Y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
Test_Data_Y

array([8, 8, 7, ..., 4, 6, 3])

In [ ]:
Test_Data_Y = to_categorical(Test_Data_Y, Valores_Diferentes)
print(Test_Data_Y)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
Capas = [64,32,10]

In [ ]:
W = Entrenar_Perceptrón_Multicapa(50, 0.1, Train_Data_X, Train_Data_Y, Capas)
print(W)

El error final es 6.012120308986343e-05
[[[-0.7727859018886409, -0.2073255204188187, 0.7161754815059613, 0.1683948686478931, -0.0008233246342266298, 0.49284748517964627, 0.5779664036039645, -0.024550524832568588, -0.6851867595347598, 0.002866800597457253, -0.778086457979182, -0.8013373882202044, -0.7235790105705378, -0.20733719174961052, -0.021015199151988684, 0.41295102534288186, -0.7134409326505871, -0.48509419936335707, 0.8604968851354067, 0.039740810058841225, 0.7695446478654038, 0.08774564459778178, 0.750037721074533, 0.6168714242103441, 0.16335454316151576, -0.28663836753219085, -0.38140703247822194, 0.2961351648192667, -0.48024139846853964, -0.19264933258626793, 0.024812620964888454, -0.9093724424215002], [-0.661058256932393, -0.03498985180646608, 0.5340929281566087, 0.24428787056763343, -0.6164062941016989, -0.24316289622642925, 0.9253062636066446, -0.018819064410908515, 0.5155547024449876, 0.16315207483862249, -0.034899723957508656, 0.07298207217465874, -0.5737879458481809, -0

In [ ]:
EO, ER = Test_Perceptrón_Multicapa(W, Test_Data_X, Test_Data_Y, Capas, Clases)

In [ ]:
Matriz_Confusión(EO, ER)

[[100   0   0   0   1   0   0   0   0   0]
 [  0 119   2   0   0   0   0   0   0   0]
 [  0   0 109   0   0   0   0   0   0   0]
 [  0   0   0 110   0   1   0   0   1   0]
 [  0   0   0   0 100   0   0   0   0   0]
 [  0   0   0   0   0 132   0   0   0   2]
 [  0   0   0   0   0   0  90   0   0   0]
 [  0   0   0   0   1   0   0 124   0   1]
 [  0   2   0   0   1   1   0   0 120   0]
 [  0   0   0   0   0   1   0   0   0 106]]


In [ ]:
Accuracy(EO, ER)

El Accuracy es 0.9875444839857651


In [ ]:
Valor_Nuevo = [0.0, 0.015625, 0.03125, 0.046875, 0.0625, 0.078125, 0.09375, 0.109375,
               0.125, 0.140625, 0.15625, 0.171875, 0.1875, 0.203125, 0.21875, 0.234375,
               0.25, 0.265625, 0.28125, 0.296875, 0.3125, 0.328125, 0.34375, 0.359375,
               0.375, 0.390625, 0.40625, 0.421875, 0.4375, 0.453125, 0.46875, 0.484375,
               0.5, 0.515625, 0.53125, 0.546875, 0.5625, 0.578125, 0.59375, 0.609375,
               0.625, 0.640625, 0.65625, 0.671875, 0.6875, 0.703125, 0.71875, 0.734375,
               0.75, 0.765625, 0.78125, 0.796875, 0.8125, 0.828125, 0.84375, 0.859375,
               0.375, 0.390625, 0.40625, 0.421875, 0.4375, 0.453125, 0.46875, 0.484375]

Predecir(Valor_Nuevo,W,Capas,Clases)

La predicción [0, 0, 0, 0, 1, 0, 0, 0, 0, 0] es de la clase 5
